name: 'Flutter FVM config action'
description: 'Action that parses an FVM config file in order to configure the subosito/flutter-action.'
author: 'Peter Leibiger'
inputs:
  path:
    description: 'Path to the FVM config file'
    required: false
    default: '.fvm/fvm_config.json'
  flavor:
    description: 'Flavor to use'
    required: false
    default: ''
outputs:
  flutterVersion:
    description: 'The version of Flutter written in the fvm configuration file'
  flutterChannel:
    description: 'The channel of Flutter written in the fvm configuration file'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'maximize'
  color: 'blue'