name: 'Flutter FVM config action'
description: 'Action that parses an FVM config file in order to configure or setup the subosito/flutter-action.'
author: 'Peter Leibiger'
inputs:
  path:
    description: 'Path to the FVM config file'
    required: false
  flavor:
    description: 'Flavor to use'
    required: false
    default: ''
  setup:
    description: 'Setup Flutter via "subosito/flutter-action"? (default: false)'
    required: false
    default: 'false'
  disable-analytics:
    description: 'Disable analytics for Flutter and Dart'
    required: false
    default: 'true'
  cache:
    description: 'Cache Flutter via "subosito/flutter-action"? (default: true - if setup is true)'
    required: false
    default: 'false'
  cache-key:
    description: 'Identifier for the Flutter SDK cache'
    required: false
    default: ''
  cache-path:
    description: 'Flutter SDK cache path'
    required: false
    default: ''
  pub-cache-key:
    description: 'Identifier for the Dart .pub-cache cache'
    required: false
    default: ''
  pub-cache-path:
    description: 'Flutter pub cache path'
    required: false
    default: default
outputs:
  FLUTTER_VERSION:
    description: 'The version of Flutter specified in the fvm configuration file'
    value: ${{ steps.config.outputs.FLUTTER_VERSION }}
  FLUTTER_CHANNEL:
    description: 'The channel of Flutter specified in the fvm configuration file'
    value: ${{ steps.config.outputs.FLUTTER_CHANNEL }}
runs:
  using: 'composite'
  steps:
    - name: Parse configuration
      uses: kuhnroyal/flutter-fvm-config-action/config@v3
      id: config
      with:
        path: ${{ inputs.path }}
        flavor: ${{ inputs.flavor }}
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      if: inputs.setup == 'true'
      with:
        flutter-version: ${{ steps.config.outputs.FLUTTER_VERSION }}
        channel: ${{ steps.config.outputs.FLUTTER_CHANNEL }}
        cache: ${{ inputs.cache }}
        cache-key: ${{ inputs.cache-key }}
        cache-path: ${{ inputs.cache-path }}
        pub-cache-key: ${{ inputs.pub-cache-key }}
        pub-cache-path: ${{ inputs.pub-cache-path }}
    - shell: sh
      if: inputs.setup == 'true' && inputs.disable-analytics == 'true'
      run: |
        flutter config --no-analytics
        dart --disable-analytics
branding:
  icon: 'maximize'
  color: 'blue'
