name: 'Flutter FVM config action'
description: 'Action that parses an FVM config file in order to configure or setup the subosito/flutter-action.'
author: 'Peter Leibiger'
inputs:
  path:
    description: 'Path to the FVM config file'
    required: false
  flavor:
    description: 'Flavor to use'
    required: false
    default: ''
  setup:
    description: 'Setup Flutter via "subosito/flutter-action"? (default: false)'
    required: false
    default: 'false'
  cache:
    description: 'Cache Flutter via "subosito/flutter-action"? (default: true - if setup is true)'
    required: false
    default: 'true'
outputs:
  FLUTTER_VERSION:
    description: 'The version of Flutter specified in the fvm configuration file'
    value: ${{ steps.config.outputs.FLUTTER_VERSION }}
  FLUTTER_CHANNEL:
    description: 'The channel of Flutter specified in the fvm configuration file'
    value: ${{ steps.config.outputs.FLUTTER_CHANNEL }}
runs:
  using: 'composite'
  steps:
    - name: Parse configuration
      uses: kuhnroyal/flutter-fvm-config-action/config@v2
      id: config
      with:
        path: ${{ inputs.path }}
        flavor: ${{ inputs.flavor }}
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      if: inputs.setup == 'true'
      with:
        cache: ${{ inputs.cache }}
        flutter-version: ${{ steps.config.outputs.FLUTTER_VERSION }}
        channel: ${{ steps.config.outputs.FLUTTER_CHANNEL }}
branding:
  icon: 'maximize'
  color: 'blue'
