name: 'Flutter FVM config action'
description: 'Action that parses an .fvmrc file in order to configure the subosito/flutter-action.'
author: 'Peter Leibiger'
inputs:
  path:
    description: 'Path to the .fvmrc config file'
    required: false
    default: '.fvmrc'
  flavor:
    description: 'Flavor to use'
    required: false
    default: ''
outputs:
  FLUTTER_VERSION:
    description: 'The version of Flutter specified in the .fvmrc file'
  FLUTTER_CHANNEL:
    description: 'The channel of Flutter specified in the .fvmrc file'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'maximize'
  color: 'blue'